# Form implementation generated from reading ui file 'GU.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(120, 90, 321, 231))
        self.groupBox.setObjectName("groupBox")
        self.id = QtWidgets.QLineEdit(parent=self.groupBox)
        self.id.setGeometry(QtCore.QRect(110, 30, 161, 20))
        self.id.setObjectName("id")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 47, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.label_4.setObjectName("label_4")
        self.hoten = QtWidgets.QLineEdit(parent=self.groupBox)
        self.hoten.setGeometry(QtCore.QRect(110, 70, 161, 20))
        self.hoten.setObjectName("hoten")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 47, 13))
        self.label_5.setObjectName("label_5")
        self.tuoi = QtWidgets.QLineEdit(parent=self.groupBox)
        self.tuoi.setGeometry(QtCore.QRect(110, 140, 161, 20))
        self.tuoi.setObjectName("tuoi")
        self.nam = QtWidgets.QRadioButton(parent=self.groupBox)
        self.nam.setGeometry(QtCore.QRect(110, 110, 82, 17))
        self.nam.setObjectName("nam")
        self.nu = QtWidgets.QRadioButton(parent=self.groupBox)
        self.nu.setGeometry(QtCore.QRect(190, 110, 82, 17))
        self.nu.setObjectName("nu")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(140, 180, 101, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Phần Mềm Nhận Diện Khuôn Mặt"))
        self.groupBox.setTitle(_translate("MainWindow", "Thông Tin Người "))
        self.label_2.setText(_translate("MainWindow", "Nhập ID"))
        self.label_3.setText(_translate("MainWindow", "Nhập Họ Tên"))
        self.label_4.setText(_translate("MainWindow", "Giới Tính"))
        self.label_5.setText(_translate("MainWindow", "Nhập Tuổi"))
        self.nam.setText(_translate("MainWindow", "Nam"))
        self.nu.setText(_translate("MainWindow", "Nữ"))
        self.pushButton.setText(_translate("MainWindow", "Thêm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
