# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 555)
        MainWindow.setStyleSheet("border-image: url(:/pic/anh-nen-cong-nghe-cho-laptop_103226961.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.P1 = QtWidgets.QPushButton(self.centralwidget)
        self.P1.setGeometry(QtCore.QRect(210, 70, 291, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.P1.setFont(font)
        self.P1.setAutoFillBackground(False)
        self.P1.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.P1.setObjectName("P1")
        self.P2 = QtWidgets.QPushButton(self.centralwidget)
        self.P2.setGeometry(QtCore.QRect(210, 190, 291, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.P2.setFont(font)
        self.P2.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.P2.setObjectName("P2")
        self.camera = QtWidgets.QPushButton(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(210, 310, 291, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.camera.setFont(font)
        self.camera.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.camera.setObjectName("camera")
        self.thoat = QtWidgets.QPushButton(self.centralwidget)
        self.thoat.setGeometry(QtCore.QRect(210, 430, 291, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.thoat.setFont(font)
        self.thoat.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.thoat.setObjectName("thoat")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("border-image: url(:/pic/background-xanh-mau-nuoc-tuyet-dep-ks533.jpg);\n"
"color: rgb(170, 170, 255);")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 70, 151, 201))
        self.stackedWidget.setStyleSheet("border-image: url(:/pic/background-xanh-mau-nuoc-tuyet-dep-ks533.jpg);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 141, 181))
        self.label_3.setStyleSheet("border-image: url(:/pic/Dio-Brando-jojos-bizarre-adventure-40409236-517-517.jpg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/test/D:/BAP TAP Python/face1/Dio-Brando-jojos-bizarre-adventure-40409236-517-517.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-image: url(:/pic/background-xanh-mau-nuoc-tuyet-dep-ks533.jpg);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 70, 141, 221))
        self.label_5.setStyleSheet("border-image: url(:/pic/ccc8d771-502b-4744-a18e-d2fd0d57899d.jpg);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/test/D:/BAP TAP Python/face1/ccc8d771-502b-4744-a18e-d2fd0d57899d.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 310, 111, 101))
        self.pushButton.setStyleSheet("border-image: url(:/pic/Wikimania2023_Animated_Sticker_Camera.gif);\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.chatbox = QtWidgets.QPushButton(self.centralwidget)
        self.chatbox.setGeometry(QtCore.QRect(700, 490, 51, 51))
        self.chatbox.setStyleSheet("border-image: url(:/pic/istockphoto-1133721644-170667a.jpg);")
        self.chatbox.setText("")
        self.chatbox.setObjectName("chatbox")
        self.url = QtWidgets.QPushButton(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(20, 320, 121, 121))
        self.url.setStyleSheet("border-image: url(:/pic/pngtree-man-holding-checklist-business-checkbox-paper-vector-png-image_10388326.png);")
        self.url.setText("")
        self.url.setObjectName("url")
        self.camera.raise_()
        self.P1.raise_()
        self.P2.raise_()
        self.thoat.raise_()
        self.stackedWidget.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.chatbox.raise_()
        self.url.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.P1.setText(_translate("MainWindow", "Bổ Sung Người Dùng"))
        self.P2.setText(_translate("MainWindow", "Quét Khuôn Mặt Người Dùng"))
        self.camera.setText(_translate("MainWindow", "CAMERA"))
        self.thoat.setText(_translate("MainWindow", "Thoát"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Palatino Linotype\'; font-size:24pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-style:italic; color:#990000;\">TRANG CHỦ</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Hình Người Quản Lý"))

import hinhanh


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
